### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by proski**
Fixing warnings to keep their number manageable. This also establishes a higher standard for the new code.

### CODE REVIEW

**Comment by jsorg71** [comment]
+1
I like it but I think __always_unused seems odd.
I see __ prefix and I think compiler define.
We can always change it later but ALWAYS_UNUSED seems better.
Or using in_uint8s(s, _bytes); /* name */ works too and with all compilers.

**Comment by proski** [comment]
I agree about compiler defines. Indeed, it would be better to use something
that looks "magic", but not "compiler-internals-magic". I had no good idea,
so I went with the Linux kernel choice. ALWAYS_UNUSED would steal attention
for more important things. It's way too big and loud.

I wanted to preserve more information about the discarded data. If that's
not a big deal, let's use a more portable solution as you suggest.

**Comment by proski** [comment]
I dropped most of the "unused" fixes, including __always_unused. I also removed changes to window_id declaration.

**Comment by jsorg71** [comment]
looks good
+1

**Comment by proski** [comment]
Can somebody merge it soon, please? If there are any questions, I can make a separate pull request for "Fix recently introduced warnings in session.c " as it's a serious issue (incorrect pointer types).

**Pull request merged**
