### PR TITLE
Convert git submodules to git subtrees

### PR DESCRIPTION
**Pull request by proski**

### CODE REVIEW

**Comment by Natureshadow** [comment]
I'd not squash the histories. Keeping full history is a good thing (and makes finding things and splitting easier for others).

**Comment by proski** [comment]
OK, the history is preserved now.

**Comment by proski** [comment]
I don't know if this patch can be merged safely. I suggest using this gist on the clean checkout and submitting the result. https://gist.github.com/proski/c1a240426d2fa58fca57116987b85d61

**Comment by jsorg71** [comment]
Do we really want to switch to subtrees?
I'm not convinced they are better.

**Comment by jsorg71** [comment]
I did read up on subtrees but the goal is to move the submodules out entirely.
I want to move them away not integrate them more tightly.
I can live with either too so I think it's up to you guys.

**Comment by proski** [comment]
Oh, I see. That makes sense. Then maybe you could merge #587 for now? It can always be reverted as the submodules are devolved. I just want to close this topic one way or another.

**Comment by jsorg71** [comment]
I'll merge that one.
@Natureshadow is pro subtree
@proski  you sound neutral, so am I.
If you other guys want subtrees lets do it but I think we should do a new PR.

**Comment by proski** [comment]
Closing this PR. If anybody wants to continue this effort, you can use my gist for conversion.

**Pull request closed without merging**
