### PR TITLE
fix for protocol error when 32 bit color and non rfx

### PR DESCRIPTION
**Pull request by jsorg71**

### CODE REVIEW

**Comment by metalefty** [comment]
Works fine. I don't see no protocol errors.

**Comment by speidy** [comment]
Wow! I totally forgot about the order size issue!

@jsorg71 Has the issue reproduced easily for you? I wonder why I didn't
face it. Might be special resolution.

+1

-- 
Idan Freiberg

PGP FP: 8108 7EC9 806E 4980 75F2  72B3 8AD3 2D04 337B 1F18

**Comment by jsorg71** [comment]
@speidy Yes, easy to reproduce.  Turn off bitmap compression in xrdp.ini and then connect at 32 bit color and no RFX.

**Comment by tfischer77** [comment]
Just had the opportunity to test. Everything is working fine, I will close #737 as soon as the Pull request has been merged.

**Comment by metalefty** [comment]
Let's merge and prepare release.

**Pull request merged**
