### PR TITLE
Make xrdp init.d work with rhel

### PR DESCRIPTION
**Pull request by bently0602**
Changed init.d script to work with redhat/centos/etc. Tested with centos 6.5. Need to change the compiling with Centos page in the wiki.

### CODE REVIEW

**Comment by itamarjp** [comment]
the options are 

1 - keep initscript into debian.
2 - include debian initscript into xrdp/instfiles/debian.init or something without replacing or changing redhat initscript

I think number 2 is the best option.

**Comment by moobyfr** [comment]
I've tried the current git with a debian jessie, there are some redhat-ish options in the support for systemd: use of /etc/sysconfig
moreover, xrdp is started with --nodaemon which makes it killed after 30s ..

**Comment by itamarjp** [comment]
moobyfr, please send a patch to fix that, closing this request for now.

**Comment by moobyfr** [comment]
the pull request exist:
https://github.com/neutrinolabs/xrdp/pull/267

**Comment by itamarjp** [comment]
merged

**Pull request closed without merging**
