### PR TITLE
xrdpapi: change WTSVirtualChannelWrite return codes to be consistent with WTSVirtualChannelRead

### PR DESCRIPTION
**Pull request by speidy**

### CODE REVIEW

**Comment by ben-cohen** [comment]
Doh, I should have checked Issues before making a [pull request](https://github.com/neutrinolabs/xrdp/pull/863/)!

@speidy - there are also two calls to WTSVirtualChannelWrite() from tcutils/utils.cpp that I think want to change as well.

**Comment by speidy** [comment]
@ben-cohen Thanks for your work :)
I'll push a fix for tcutils.c, I missed it somehow.

**Comment by metalefty** [comment]
The Travis failure is false-positive. I'll look at it.

**Comment by metalefty** [comment]
I've applied the fix to devel branch. Rebase this PR to the latest devel to perform build test.

**Comment by metalefty** [comment]
Let's merge.

**Pull request merged**
