### PR TITLE
sesman: unbreak FreeBSD build after #523

### PR DESCRIPTION
**Pull request by metalefty**
`username` here should be changed to `s->username`, too.

### CODE REVIEW

**Comment by metalefty** [comment]
The change was introduced by 57905d7.

**Comment by jsorg71** [comment]
opps, sorry about that
+1

**Comment by proski** [comment]
+1

**Comment by metalefty** [comment]
No problem. I should have realize it in review.
I'll merge this shortly because it's a small change and fixes build failure.

**Pull request merged**
