### PR TITLE
Increase timeouts for some tests

### PR DESCRIPTION
**Pull request by elboulangero**

### CODE REVIEW

**Comment by matt335672** [comment]
@metalefty - we're waiting for feedback on this. See #2213

**Comment by metalefty** [comment]
I see. Thank you for letting me know the current status.

**Comment by matt335672** [comment]
Some more analysis.

At the moment, all the SSL calls are lumped together in one test suite which has a common timeout.

I can reproduce this by running the test suite under valgrind to simulate a slow machine. What I'm finding is that pretty much all the time is being taken up in `ssl_gen_key_xrdp1()`. Drilling into this, all the time is being generated in the call to `EVP_PKEY_generate()` (i.e. in the SSL library call).

I've got a Xeon E3-1275 v3 which is about a decade old now. On that, the call to `EVP_PKEY_generate()` normally takes 150ms, but amazingly takes 15-30 seconds under valgrind. The next slowest test under valgrind in this suite is `test_sha1_hash_ok()` at 112ms.

I'll put together a more nuanced version of this PR to split the test case up a bit and add an extended timeout to the `ssl_gen_key_xrdp1()` case only.

**Comment by matt335672** [comment]
Closing this - see #2901 which replaces it.

**Pull request closed without merging**
