### PR TITLE
Switch to 8 hex digit keymapfile

### PR DESCRIPTION
**Pull request by metalefty**
as the value keyboardLayout is actually 32-bit unsigned integer.
See [MS-RDPBCGR] - v20160714 p.45.

### CODE REVIEW

**Comment by metalefty** [comment]
I and proski suggested switching to 8 hex digit format for all km*.ini files.

**Comment by metalefty** [comment]
Chase #453.

**Comment by metalefty** [comment]
@jsorg71 @itamarjp what do you think of?

**Comment by itamarjp** [comment]
for me looks good to keep in sync with https://goo.gl/4rQByJ

**Comment by proski** [comment]
Looks good to me.

**Comment by metalefty** [comment]
Jay, could you merge this if you agree to switch?

**Pull request merged**
