### PR TITLE
Prepare 0.9.2 - for testing only, not for merging

### PR DESCRIPTION
**Pull request by proski**

### CODE REVIEW

**Comment by proski** [comment]
Tarball generated by `make distcheck` attached for testing. Please be careful not to confuse it with an official release.
[xrdp-0.9.2.tar.gz](https://github.com/neutrinolabs/xrdp/files/878091/xrdp-0.9.2.tar.gz)

**Comment by Natureshadow** [comment]
>Tarball generated by `make distcheck` attached for testing. Please be
>careful not to confuse it with an official release.
>[xrdp-0.9.2.tar.gz](https://github.com/neutrinolabs/xrdp/files/878091/xrdp-0.9.2.tar.gz)

Then don't give it the version of a stable release...

**Comment by speidy** [comment]
Regarding submodules, we need to merge the version bump PRs first then update here

**Comment by proski** [comment]
@Natureshadow my bad, I removed my comment. But your comment is still referring to that file, and I cannot remove it. It looks like we are going to have a real release in a few hours anyway.

**Pull request closed without merging**
