### PR TITLE
common: change g_malloc, g_free, g_memset, g_memcpy, and g_memmove to…

### PR DESCRIPTION
**Pull request by jsorg71**
… macros.  This should allow compilers to optimize these calls.

### CODE REVIEW

**Comment by matt335672** [comment]
@metalefty - do you want this in teh v0.9 branch as well?

**Comment by metalefty** [comment]
I think it would be nice if we can have benefits from compiler optimization. Let's take this to v0.9 branch.

**Comment by Nexarian** [comment]
Curious: How much of a performance gain do we think we'll get from this compiler optimization?

**Comment by matt335672** [comment]
Not a vast amount, but we may well get some code shrinkage (which will have caching benefits). The compiler can optimise copies of small fixed memory sizes into one or more move instructions, avoiding a function call.

This is also a step to moving to #2499 - using library functions makes it (hopefully) easier to attract other contributions, although we've got a long way to go on this!

**Pull request merged**
