### PR TITLE
support mousex button 8/9

### LINKED ISSUE #1477: mouse forward/back button and horizontal scroll
my mouse has no horizontal scroll function, but has forward/back button.
when using mstsc with xrdp, I found  forward/back button event was transfer as button 6/7 in `xrdp_wm_process_input_mousex`
```c
    if (device_flags & PTRXFLAGS_DOWN)
    {
        if (device_flags & PTRXFLAGS_BUTTON1)
        {
            xrdp_wm_mouse_click(self, x, y, 6, 1);
        }
        else if (device_flags & PTRXFLAGS_BUTTON2)
        {
            xrdp_wm_mouse_click(self, x, y, 7, 1);
        }
    }
    else
    {
        if (device_flags & PTRXFLAGS_BUTTON1)
        {
            xrdp_wm_mouse_click(self, x, y, 6, 0);
        }
        else if (device_flags & PTRXFLAGS_BUTTON2)
        {
            xrdp_wm_mouse_click(self, x, y, 7, 0);
        }
    }
```
but in `xrdp_wm_process_input_mousex`, button 6/7 was described as horizontal scroll. and it's will be trigger multiple times when press up/down mouse button
```c
                /* horizontal scroll */

                if (but == 6)
                {
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON6DOWN,
                                             self->mouse_x, self->mouse_y, 0, 0);
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON6UP,
                                             self->mouse_x, self->mouse_y, 0, 0);
                }

                if (but == 7)
                {
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON7DOWN,
                                             self->mouse_x, self->mouse_y, 0, 0);
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON7UP,
                                             self->mouse_x, self->mouse_y, 0, 0);
                }
```
it lead that in linux desktop, I will got keypress and keyrelease event when I PRESS button, and after I release the button, it's got a keypress and keyrelease event again.

### PR DESCRIPTION
**Pull request by okhowang**
resolve #1477
do not reuse button 6/7 with button of mousex event
button 8/9 is used widely as back/forward button

### CODE REVIEW

**Comment by metalefty** [comment]
Great. Good first-issue.

**Comment by metalefty** [comment]
@okhowang BTW, what mouse do you use? I would like to buy one to test.

**Comment by okhowang** [comment]
I have test with [http://www.deluxworld.com/en/product/rgzn/czsb/65.html](http://www.deluxworld.com/en/product/rgzn/czsb/65.html)
and apple mouse magic on windows with mstsc

**Comment by metalefty** [comment]
Thanks, I have apple magic mouse. I would be able to test it.

**Pull request merged**
