### PR TITLE
Add libpainter submodule, update librfxcodec URL

### PR DESCRIPTION
**Pull request by proski**
This PR prepares the stage for the noorders branch. Moving back and forth through a commit that adds a submodule is quite painful, so let's get it merged so that further changes can be tested easily.

I used the latest commit of libpainter. It includes a fix for "make distcheck".

I also changes the git protocol used for librfxcodec from git to https. The git protocol is a bad choice in my opinion. See this writeup for example: https://gist.github.com/grawity/4392747

GitHub doesn't even advertise the git protocol. It recommends https. https://help.github.com/articles/which-remote-url-should-i-use/

This PR is for version 0.9.1, since we want noorders to be part of 0.9.1.

### CODE REVIEW

**Comment by metalefty** [comment]
+1 to https. I also replace `git://` URLs to `https://` in RH-Matic.

**Comment by metalefty** [comment]
any objections to merge?

**Comment by jsorg71** [comment]
+1

**Comment by speidy** [comment]
+1

**Pull request merged**
