### PR TITLE
docs: remove IdleTimeLimit until it is actually implemented

### PR DESCRIPTION
**Pull request by metalefty**
it gives users false hope and finally disappoints them.

### CODE REVIEW

**Comment by proski** [comment]
+1

The configuration files and the manuals are not the right place for TODO lists.

Please note that there are still references to `IdleTimeLimit`, `max_idle_time`, and `XRDP_SESMAN_MAX_IDLE_TIME` in the code. If nobody plans to implement idle timeout, they should be removed too.

**Comment by metalefty** [comment]
I think everything to support idle timeout is done in xrdp (as frontend). The rest part should be done in xorgxrdp/x11rdp.  We can remove such code and whenever resurrect it from git history if implementation is done in backend.

**Comment by proski** [comment]
OK, let's merge

**Comment by metalefty** [comment]
No logic change, merging immediately.

**Pull request merged**
