### PR TITLE
add TS_ to INPUT constants in xrdp_constants.h

### PR DESCRIPTION
**Pull request by jsorg71**

### CODE REVIEW

**Comment by jsorg71** [comment]
fix for #931

**Comment by metalefty** [comment]
I thought you were going to respect the original document. If the original constant has TS_ prefix and the prefix removed in xrdp, resurrect the prefix. Am I misunderstood?

**Comment by jsorg71** [comment]
Yes, so we don't need this PR.  If we're all good,  I'll delete this after day or so and close #931

**Comment by metalefty** [comment]
BTW, I have some thoughts on constants.  I'll raise a new issue and let's discuss.

**Pull request closed without merging**
