### PR TITLE
Improve RDS compatibility

### PR DESCRIPTION
**Pull request by matt335672**
Port of #2266 to the 0.9 branch.

Is this the right place for it @metalefty? If so please merge.

### CODE REVIEW

**Comment by matt335672** [comment]
I think we also need #2226 porting over before this one to fix the CI.

**Comment by metalefty** [comment]
Indeed.

**Comment by matt335672** [comment]
OK - for now I've just added this to the v0.9.20 milestone, like #2226. This one is however, based on v0.9.19 rather than devel.

**Comment by matt335672** [comment]
I've updated the NEWS page, and tried to make it clear the next major version is based on v0.9.19

**Pull request merged**
