### PR TITLE
More integration work from mainline_merge_shm

### PR DESCRIPTION
**Pull request by Nexarian**
Mostly refactoring and slowly introducing idioms necessary for GFX to work.

### CODE REVIEW

**Comment by metalefty** [comment]
Will CI failures be fixed later?

**Comment by Nexarian** [comment]
Yeah, sorry, I've moved this back to draft. Still WIP

**Comment by Nexarian** [comment]
Ok I've updated this pull request. Still not completely working as tested; however, please review so far.

**Comment by metalefty** [comment]
Let's merge and go ahead.

**Comment by Nexarian** [comment]
With this change RFX Pro should work, not perfectly, but it does work.

**Pull request merged**
