### PR TITLE
Split sesman into sesman and sesexec

### LINKED ISSUE #350: Homedir gets not correctly created at first login
I'm opening this as a new issue, although my problems have already been started to be discussed at #325 which has been marked as "closed" before finding a solution for my specific problem.

Short summary here:

I built xrdp upstream version and have a problem when connecting to the server for the very first time with a user. The server should then create a homedir (via pam_mkhomedir). The server is a member of an active directory, PAM is configured to authenticate via samba/winbind and create home directories for users on their first login. This works perfectly for e.g. ssh or other services but not for xrdp. 

I had a look at bugs #182 and #196 which seem similar but have a different background. The problem of these referenced bugs is that VNC needs some time to start up before connecting to it - so a timeout (loop) has been implemented. This is not the case here. 

In this bug, VNC starts but there seems to be a problem with the order a full PAM based authentification. xrdp is supposed to first do the PAM authentication (which would initially creating a users' home directory) and then start VNC. This seems not to work as expected somehow... In general, the home directory gets created somewhen, but obviously too late in the process so that VNC spits out the error lines

```
[20160229-15:51:49] [ERROR] env_set_user: error creating .vnc dir
[20160229-15:51:49] [WARN ] can't write vnc password hash file - /home/DOMAIN/username/.vnc/sesman_username_passwd
```

If I kill the Xvnc process (or completely restart xrdp) and try it again (after the homedir got created while the first login try), it works. If I create the user's home directory manually it also works.

I wasn't able to let PAM create the homedir before VNC starts, I tried almost every possible order of "session" entries (especially those with pam_mkhomedir.so at the beginning).

### LINKED ISSUE #1323: pam_setcred never returns xrdp-sesman is hung
When I try to connect via RDP Win10 client, a forked xrdp-sesman process gets hung.  This is a fresh mac-mini late 2012 which I immediately updated to Mojave.   I spent a few days now debugging and figuring out why the RDP connection never succeeds, which from the clients point of view times out after 30 seconds.  I've discovered that the call to pam_setcred in auth_start_session never returns.  The stack trace is this:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff5d6e0266 libsystem_kernel.dylib`semaphore_wait_trap + 10
    frame #1: 0x00007fff5d55ebd9 libdispatch.dylib`_dispatch_sema4_wait + 16
    frame #2: 0x00007fff5d55f3a0 libdispatch.dylib`_dispatch_semaphore_wait_slow + 98
    frame #3: 0x00007fff397c256c CFOpenDirectory`transaction_simple + 370
    frame #4: 0x00007fff397c2335 CFOpenDirectory`_ODNodeExternalCreate + 180
    frame #5: 0x00007fff397c1fc8 CFOpenDirectory`node_cache_get_and_retain + 194
    frame #6: 0x00007fff397c1edf CFOpenDirectory`_ODNodeInit + 323
    frame #7: 0x00007fff397c1c33 CFOpenDirectory`ODNodeCreateWithNameAndOptions + 157
    frame #8: 0x00007fff5cc9dfd5 pam_ntlm.so.2`od_record_create + 98
    frame #9: 0x00007fff5cc9e36e pam_ntlm.so.2`od_record_create_cstring + 60
    frame #10: 0x00007fff5cc9f148 pam_ntlm.so.2`pam_sm_setcred + 290
    frame #11: 0x00007fff5c50dd64 libpam.2.dylib`openpam_dispatch + 500
    frame #12: 0x00000001014335b5 xrdp-sesman`auth_start_session(in_val=140346661011824, in_display=10) at verify_user_pam.c:205:13
    frame #13: 0x000000010143037c xrdp-sesman`session_start_fork(data=140346661011824, type='\x03', c=0x00007ffeee7d3760, s=0x00007fa500e000b0) at session.c:478:9
    frame #14: 0x00000001014300a1 xrdp-sesman`session_start(data=140346661011824, type='\x03', c=0x00007ffeee7d3760, s=0x00007fa500e000b0) at session.c:912:12
    frame #15: 0x000000010142ed2f xrdp-sesman`scp_v0_process(c=0x00007ffeee7d3760, s=0x00007fa500e000b0) at scp_v0.c:0:21 [opt]
    frame #16: 0x000000010142ea3f xrdp-sesman`scp_process_start(sck=<unavailable>) at scp.c:62:17 [opt]
    frame #17: 0x000000010142f53a xrdp-sesman`sesman_main_loop at sesman.c:154:25 [opt]
    frame #18: 0x000000010142fb94 xrdp-sesman`main(argc=<unavailable>, argv=<unavailable>) at sesman.c:446:13 [opt]
    frame #19: 0x00007fff5d5ab3d5 libdyld.dylib`start + 1
```

Maybe I have something misconfigured, though I didn't change much.  However, I don't think it shouldn't hang, right?  Any tips how to debug further?  I've tried turning on the debug info for pam_ntlm.so, but while it did create a debug log, there's no extra information regarding the xrdp_sesman process.

I'm still digging, but I can't believe I'm the only one trying to run this on MacOS?  Does anybody else have success running XRDP on Mojave and connecting from a Windows machine?

Thanks - Paul

### LINKED ISSUE #1684: No user session created with xrdp and pam_systemd_home account module
Thanks for a great program!  Newbie here, apologies for any inaccuracies.  A recent change to the PAM configuration files in Arch repositories seems to be causing problems with xrdp.  The current version of `/etc/pam.d/system-auth` contains the following `account` section:

```
-account   [success=1 default=ignore]  pam_systemd_home.so
account    required                    pam_unix.so
account    optional                    pam_permit.so
account    required                    pam_time.so
```

The first line, `-account   [success=1 default=ignore]  pam_systemd_home.so`, results in no user session being created in xrdp.  The output of `loginctl session-status` is `Could not get properties: Unknown object '/org/freedesktop/login1/session/auto'.`  This causes problems like being unable to start a polkit authentication agent.

For debug purposes, I’ve changed the malfunctioning `pam_systemd_home.so` line to `account   [default=ignore]  pam_systemd_home.so debug`.  `journalctl` shows the following in what I think relevant part when connecting to xrdp:

```
Sep 08 18:13:45 bigone xrdp-sesman[642]: pam_systemd_home(xrdp-sesman:account): pam-systemd-homed account management
Sep 08 18:13:45 bigone dbus-daemon[618]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.1543' (uid=0 pid=642 comm="/usr/bin/xrdp-sesman --nodaemon ")
Sep 08 18:13:45 bigone dbus-daemon[618]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service': Unit dbus-org.freedesktop.home1.service not found.
Sep 08 18:13:45 bigone xrdp-sesman[642]: pam_systemd_home(xrdp-sesman:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Sep 08 18:13:45 bigone xrdp-sesman[642]: (642)(140313509857088)[INFO ] ++ created session (access granted): username esyu, ip 192.168.84.210:64145 - socket: 12
Sep 08 18:13:45 bigone xrdp-sesman[642]: (642)(140313509857088)[INFO ] starting Xvnc session...
Sep 08 18:13:45 bigone xrdp-sesman[642]: (642)(140313509857088)[DEBUG] Closed socket 38 (AF_INET 0.0.0.0:5910)
Sep 08 18:13:45 bigone xrdp-sesman[23600]: (23600)(140313509857088)[INFO ] calling auth_start_session from pid 23600
Sep 08 18:13:45 bigone xrdp[645]: (645)(140514163267136)[INFO ] xrdp_wm_log_msg: login successful for display 10
Sep 08 18:13:45 bigone xrdp-sesman[23600]: pam_systemd(xrdp-sesman:session): Failed to create session: No child processes
Sep 08 18:13:47 bigone xrdp-sesman[23731]: Failed to connect to session manager: Failed to connect to the session manager: Could not open network socket
Sep 08 18:13:52 bigone xrdp-sesman[23731]: xfsettingsd: No window manager registered on screen 0.
Sep 08 18:13:52 bigone xfsettingsd[23731]: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
```

If the `pam_systemd_home.so` line is removed, everything works fine.  Note that I do not have `systemd-homed` running.  Xorg vs Xvnc makes no difference, nor does having a `startwm.sh` with just `exec xterm` in it.

Not sure if this is an xrdp problem or something else; for what it’s worth, local login and ssh work fine.

Additional info:

- OS and version: Manjaro 18.0 XFCE Edition
- xrdp version: 0.9.14
- xorgxrdp version: 0.2.14
- Client OS / Client software: Windows 10 Remote Desktop Connection
- Desktop: Xfce (but likely irrelevant; even `xterm` fails)
- Backend: Both Xorg and Xvnc

### PR DESCRIPTION
**Pull request by matt335672**
**Edit 2/5/23**: No longer draft

Fixes #1684 (after 2-and-a-half years) and possibly other issues.

Implements most of the [new authentication architecture](/matt335672/xrdp/wiki/Authentication-architecture-redesign) without the interactive PAM dialog.

sesman is now two executables:-
- xrdp-sesman is responsible for managing session lists and responding to user requests over SCP
- xrdp-sesexec is responsible for user authentication and authorization, and managing a single session. It lives in libexecdir.

Here's a brief description of the main features. There's a link below with more information.

## ECP (Executive Control Protocol)
The new protocol between sesman and sesexec (ECP) is divided into two sub-protocols:-
- EICP (Executive initialization control protocol) is used by sesman to ask sesexec authenticate a user (username/password) and start a session.
- ERCP (Executive runtime control protocol) is used for run-time session management.

The reason for this separation is security. Either a session is active, or it isn't. ERCP is pretty bare at the moment but it will support more messages in the future.

## Debugging sesexec
sesexec can be debugged in the following ways (that's I've used so far):-
1) Attaching a debugger at run-time
2) Starting sesexec under control of a debugger
3) Running sesexec through `valgrind`

I'm aware this is a challenge to review. If you think I can make it any easier in any way, please  let me know.

### CODE REVIEW

**Comment by matt335672** [comment]
Update : -
1) As promised, more detailed documentation on implementation details can be found at https://github.com/matt335672/xrdp/wiki/Session-management-architecture. Comments welcome. I can move this to the main wiki later.
2) I've now tested session management is OK on FreeBSD 12 and 13. @metalefty put a bit of work into getting this right for [#251](/neutrinolabs/xrdp/pull/251). All the code is still in, but it's now split up a bit.

**Comment by matt335672** [comment]
Given the size of this, I can understand it's a lot to look at.

Also, given we're some way from releasing V1.x, I propose to merge this towards the end of the week unless anyone objects. That should give us time to get the major wrinkles out.

Please say something if you don't think this is a good idea.

**Comment by metalefty** [comment]
I'm fine with merging this. Thanks for your hard work.

**Comment by matt335672** [comment]
Thanks - merged.

**Pull request merged**
