### PR TITLE
fix valgrind warning on font

### PR DESCRIPTION
**Pull request by jsorg71**

### CODE REVIEW

**Review by Nexarian — APPROVED** [review]

**Comment by metalefty** [comment]
LGTM. @matt335672 is working around this code but I think it doesn't conflict.

**Comment by jsorg71** [comment]
Here is the output from valgrind, line numbers might not be exact as I found this in another branch.
```
[2023-09-23T16:47:44.564-0700] [WARN ] No DPI value is available to find login font
[2023-09-23T16:47:44.605-0700] [WARN ] Using the default_dpi of 96
==21800== Thread 2:
==21800== Invalid read of size 2
==21800==    at 0x483A0D8: memcpy@GLIBC_2.2.5 (vg_replace_strmem.c:1033)
==21800==    by 0x112AB1: xrdp_cache_add_char (xrdp_cache.c:586)
==21800==    by 0x120630: xrdp_painter_draw_text (xrdp_painter.c:938)
==21800==    by 0x10F60B: xrdp_bitmap_invalidate.part.0 (xrdp_bitmap.c:706)
==21800==    by 0x10F2C8: xrdp_bitmap_invalidate (xrdp_bitmap.c:613)
==21800==    by 0x10F621: xrdp_bitmap_invalidate.part.0 (xrdp_bitmap.c:1005)
==21800==    by 0x10F2C8: xrdp_bitmap_invalidate (xrdp_bitmap.c:613)
==21800==    by 0x125CB5: xrdp_wm_init (xrdp_wm.c:805)
==21800==    by 0x1264DA: xrdp_wm_login_state_changed (xrdp_wm.c:2054)
==21800==    by 0x1264DA: xrdp_wm_check_wait_objs (xrdp_wm.c:2331)
==21800==    by 0x121F13: xrdp_process_main_loop (xrdp_process.c:287)
==21800==    by 0x115606: xrdp_process_run (xrdp_listen.c:152)
==21800==    by 0x4D4AFA2: start_thread (pthread_create.c:486)
==21800==  Address 0x5655250 is 0 bytes inside a block of size 1 alloc'd
==21800==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==21800==    by 0x11548E: xrdp_font_create (xrdp_font.c:264)
==21800==    by 0x125963: xrdp_wm_init (xrdp_wm.c:586)
==21800==    by 0x1264DA: xrdp_wm_login_state_changed (xrdp_wm.c:2054)
==21800==    by 0x1264DA: xrdp_wm_check_wait_objs (xrdp_wm.c:2331)
==21800==    by 0x121F13: xrdp_process_main_loop (xrdp_process.c:287)
==21800==    by 0x115606: xrdp_process_run (xrdp_listen.c:152)
==21800==    by 0x4D4AFA2: start_thread (pthread_create.c:486)
==21800==    by 0x4C7A06E: clone (clone.S:95)
==21800==
==21800== Invalid read of size 1
==21800==    at 0x483C035: __memcmp_sse4_1 (vg_replace_strmem.c:1111)
==21800==    by 0x1155C5: xrdp_font_item_compare (xrdp_font.c:360)
==21800==    by 0x11299B: xrdp_cache_add_char (xrdp_cache.c:553)
==21800==    by 0x120630: xrdp_painter_draw_text (xrdp_painter.c:938)
==21800==    by 0x10F60B: xrdp_bitmap_invalidate.part.0 (xrdp_bitmap.c:706)
==21800==    by 0x10F2C8: xrdp_bitmap_invalidate (xrdp_bitmap.c:613)
==21800==    by 0x10F621: xrdp_bitmap_invalidate.part.0 (xrdp_bitmap.c:1005)
==21800==    by 0x10F2C8: xrdp_bitmap_invalidate (xrdp_bitmap.c:613)
==21800==    by 0x125CB5: xrdp_wm_init (xrdp_wm.c:805)
==21800==    by 0x1264DA: xrdp_wm_login_state_changed (xrdp_wm.c:2054)
==21800==    by 0x1264DA: xrdp_wm_check_wait_objs (xrdp_wm.c:2331)
==21800==    by 0x121F13: xrdp_process_main_loop (xrdp_process.c:287)
==21800==    by 0x115606: xrdp_process_run (xrdp_listen.c:152)
==21800==  Address 0x5655251 is 0 bytes after a block of size 1 alloc'd
==21800==    at 0x4837B65: calloc (vg_replace_malloc.c:752)
==21800==    by 0x11548E: xrdp_font_create (xrdp_font.c:264)
==21800==    by 0x125963: xrdp_wm_init (xrdp_wm.c:586)
==21800==    by 0x1264DA: xrdp_wm_login_state_changed (xrdp_wm.c:2054)
==21800==    by 0x1264DA: xrdp_wm_check_wait_objs (xrdp_wm.c:2331)
==21800==    by 0x121F13: xrdp_process_main_loop (xrdp_process.c:287)
==21800==    by 0x115606: xrdp_process_run (xrdp_listen.c:152)
==21800==    by 0x4D4AFA2: start_thread (pthread_create.c:486)
==21800==    by 0x4C7A06E: clone (clone.S:95)

```

**Review by metalefty — APPROVED** [review]
Approved but let's wait for @matt335672

**Comment by matt335672** [comment]
Yup - we definitely need this. I introduced this bug, so apologies for that.

@jsorg71 - meta and I are looking at a potential security issue in another thread. Because of the way github publishes security information, it's not visible to the whole team which is a pity.

I'm going to merge this now and check it doesn't conflict with anything else.

**Comment by matt335672** [comment]
BTW - this code isn't in V0.9 so we don't need to backport this.

**Comment by metalefty** [comment]
I agree.

**Comment by matt335672** [comment]
I've updated the devel branch in the private fork and rebased my change. There were no actual conflicts but I've added a comment to the code where the alloc is done for the blank glyph.

**Comment by metalefty** [comment]
@matt335672  ~~As far as I looked v0.9 code, I think backport is not required.~~

https://github.com/neutrinolabs/xrdp/blob/v0.9/xrdp/xrdp_font.c#L137-L150

**Comment by metalefty** [comment]
Ah, maybe we need to add this block?

```C
                if (datasize == 0)
                {
                    /* Allocate a single blank pixel for the glyph, so
                     * that it can be added to the glyph cache if required */
                    f->width = 1;
                    f->height = 1;
                    f->data = (char *)g_malloc(1, 1);
                    f->data = (char *)g_malloc(FONT_DATASIZE(f), 1);
                }
```

**Comment by matt335672** [comment]
Hi @metalefty

For v0.9 we're using the older fonts which are generated on Windows. As a result, `datasize` is never zero, and so we don't need to consider this case.

The move away from the fonts generated on Windows was part of #2341.

**Comment by metalefty** [comment]
Thanks for the confirmation!

**Pull request merged**
