### PR TITLE
[Test only] 0.9.1 test

### PR DESCRIPTION
**Pull request by proski**
This branch is for testing changes that are planned to be included in version 0.9.1.

### CODE REVIEW

**Comment by Natureshadow** [comment]
Should I upload a build of this branch to Debian unstable to get people test it?

**Comment by proski** [comment]
Good idea. But let's test it for ourselves first. I started seeing reconnect issues with VNC. Let's try to fix it before giving this code to Debian testers.

**Comment by proski** [comment]
Now we can upload this branch to Debian unstable. Please make sure to use `--enable-painter` to enable the new noorders functionality.

**Comment by speidy** [comment]
I think we should also include #539

**Comment by proski** [comment]
Update to the current remaining PRs. No more fixups, everything is in PRs.

**Comment by proski** [comment]
All patches have been applied, the "devel" branch can be used for testing now. Closing this PR.

**Pull request closed without merging**
