### PR TITLE
handle TS_SUPPRESS_OUTPUT_PDU

### PR DESCRIPTION
**Pull request by jsorg71**
Pass suppress event to xrdp modules.  Allows xrdp backends to handle the suppress

### CODE REVIEW

**Comment by jsorg71** [comment]
I wonder if we should put in
```
diff --git a/libxrdp/xrdp_caps.c b/libxrdp/xrdp_caps.c
index 4d1ab45..1c0587f 100644
--- a/libxrdp/xrdp_caps.c
+++ b/libxrdp/xrdp_caps.c
@@ -810,7 +810,8 @@ xrdp_caps_send_demand_active(struct xrdp_rdp *self)
     out_uint16_le(s, 0); /* Update capability */
     out_uint16_le(s, 0); /* Remote unshare capability */
     out_uint16_le(s, 0); /* Compression level */
-    out_uint16_le(s, 0); /* Pad */
+    out_uint8(s, 1); /* refreshRectSupport */
+    out_uint8(s, 1); /* suppressOutputSupport */
 
     /* Output bitmap capability set */
     caps_count++;

```
The clients don't seem to require it.

**Comment by metalefty** [comment]
Just in case, please don't merge this until I make a April release.

**Comment by jsorg71** [comment]
Ok, I'll add the above and test for a while.
Rebase or squash when ready.

**Comment by jsorg71** [comment]
Added suppress support in VNC and RDP modules for RDP to VNC and RDP to RDP proxies.  Added support in NeutrinoRDP too as a client.  Only missing suppress support in X11rdp back end currently currently.  Do we need it?

**Comment by metalefty** [comment]
@jsorg71 I think xorgxrdp is enough.

BTW, I've released v0.9.10. Feel free to merge supress support if you think it merge ready.

**Comment by metalefty** [comment]
I confirmed suppress works fine with xorgxrdp v0.2.10. Confirmed with mstsc 10.0.17763 on Windows 10.

**Pull request merged**
