### PR TITLE
Support and document SIGHUP for xrdp-sesman

### LINKED ISSUE #2414: instfiles/xrdp-sesman.service.in has no ExecReload entry
While xrdp-sesman can reread its configuration file upon reception of a SIGHUP the service file doesn't take advantage of this and the documentation doesn't mention it.
I just kicked 50 people from one of our servers because I (stupidly) believed what "systemctl reload xrdp-sesman.service" told me.
After restarting xrdp-sesman I had to manually cleanup the fallout of the orphaned sessions.
To my surprise I just found code in sesman that will do the right thing when receiving SIGHUP.

### PR DESCRIPTION
**Pull request by matt335672**
Fixes #2414

@yxzzx - can you take a look at this please?

### CODE REVIEW

**Comment by yxzzx** [comment]
Isn't it a little bit asymmetric to do the kill with "xrdp-sesman --kill" and the reload with "kill -HUP $MAINPID". I think it would be cleaner to either remove the "--kill" code from sesman or add a "--reload" option to sesman. But that's probably just me being my usual obsessive-compulsive self...

Anyway, I think your commit will be doing the job just fine. Thanks for the fix and the documentation.

**Comment by matt335672** [comment]
Hi @yxzzx 

Thanks for the swift reply.

No - that's a very good point. It absolutely should be consistent. Leave it with me.

**Review by metalefty — COMMENTED** [review]
Changes LGTM.

BTW, is the log file reopened after reloading?

**Comment by matt335672** [comment]
The code for a log restart was added for 2484928a5a47f5dba5ddd087d893c6c968b35dbb :-

https://github.com/neutrinolabs/xrdp/blob/4ff968bc980f6ff72c2e8312ce98ed67c2f6f9d8/common/log.c#L727-L782

Since the log file is shared, we never change it, as we've got no way of telling any child processes that the log file has changed. If the user tries to change it we log a warning and carry on using the old one.

That's the current behaviour anyway.

**Comment by danielperna84** [comment]
Will this also affect #1317 ?

**Comment by matt335672** [comment]
@danielperna84 - thanks for the heads-up.

As far as I can tell, #1317 isn't actually a problem. More information would be required to figure out exactly what was going on there.

**Pull request merged**
