### PR TITLE
Add support for input event unicode

### PR DESCRIPTION
**Pull request by ricardoteixeiraduarte**
Adds support for INPUT_EVENT_UNICODE

### CODE REVIEW

**Comment by ricardoteixeiraduarte** [comment]
I'm not very happy with the way I'm handling the "shift" key.
The current code sends a Shift KEY_DOWN (scancode 42) before sending the real key, and then a KBD_FLAG_UP after the key is processed.

**Comment by jsorg71** [comment]
This might be a good start but this is only one keymap.
A better solution might be to use the keymap files.
xrdp/instfiles/km-0409.ini for example, Key10=49:49, the last value, 49, is the unicode, the first value, 10(from key10), is the keycode, the second value which does not matter here is the x11 keysym.
The [noshift] section, just send as they are, the [shift] section send a shift first, even [altgr] should work, just send altgr first.
xrdp/lang.c is were we have been processing these files.

**Comment by jsorg71** [comment]
```
+    if (!s_check_rem(s, 1))
+    {
+        return 1;
+    }
+    in_uint8(s, code); /* keyCode (1 byte) */
```
This is wrong, the unicode value should be 2 bytes

**Comment by jsorg71** [comment]
The caps bits is missing from this patch
We need to set INPUT_FLAG_UNICODE.
Without it, the client should not send unicode input.

**Comment by jsorg71** [comment]
@ricardoteixeiraduarte  can you check if 2c3d4a9 work for you.
I tested with MS client on Android.  I can't get Parallels client working.

**Comment by ricardoteixeiraduarte** [comment]
Working great.

**Comment by metalefty** [comment]
@jsorg71 @ricardoteixeiraduarte  Implemented  in 2c3d4a9, so can this be closed? Or anything else neeed to be done?

**Comment by jsorg71** [comment]
This is done

**Pull request closed without merging**
