### PR TITLE
chansrv: remove pulseaudio modules from xrdp source tree

### PR DESCRIPTION
**Pull request by speidy**
its actually an independent code which is not part of xrdp
moved to its own repoistory: https://github.com/neutrinolabs/pulseaudio-modules

Signed-off-by: Idan Freiberg <speidy@gmail.com>

### CODE REVIEW

**Comment by speidy** [comment]
@metalefty remove from Makefile.am thanks

**Comment by speidy** [comment]
@metalefty updated wiki page, updated readme in pulseaudio-modules repo (neutrinolabs/pulseaudio-modules#1)

**Comment by speidy** [comment]
merge?

**Comment by metalefty** [comment]
yep!

**Pull request merged**
