### PR TITLE
Further cherry-picks for v0.10

### PR DESCRIPTION
**Pull request by matt335672**
Backports the following PRs from the devel branch:-
- #3082
- #3086
- #3103
- #3104
- #3107
- #3112

### CODE REVIEW

**Comment by metalefty** [comment]
Let's merge this to fix CI test in v0.10 branch.

**Comment by matt335672** [comment]
@metalefty - can you hold off on a new release for a bit? I'm testing a fix for #3118

**Comment by metalefty** [comment]
No problem. I just wanted to merge #3104 into the branch. I'm not going to make a new release yet.

**Comment by matt335672** [comment]
Thanks.

In any case, I've tested the fix. Please feel free to merge it too.

I've got an appointment IRL for a couple of hours. When I get back I'll update the NEWS for v0.10

**Pull request merged**
