### PR TITLE
xrdp-chansrv crashes under musl libc

### PR DESCRIPTION
**Pull request by bblackcblackc**
xrdp-chansrv crashes when compiled against musl libc. This patch is preventing crash by setting stack size equals to GLIBC (8Mb) and set guard page.

### CODE REVIEW

**Comment by bblackcblackc** [comment]
deleted _GNU_SOURCE definition

**Comment by metalefty** [comment]
Please cleanup commits.

**Comment by bblackcblackc** [comment]
> Please cleanup commits.

Merge all commits to once or what?

**Comment by metalefty** [comment]
Please do not leave your trials and errors such as 8b95cb261dc954d45d04346e4bef828d4ce59af4 and f83c60d4815433519742cb004e5b1d5364d750fc,

**Comment by metalefty** [comment]
You add something in the PR and then you remove it.
If you finally remove it in the PR, you don't need to add it fundamentally.

**Comment by metalefty** [comment]
No feedback from the submitter, closing.

**Pull request closed without merging**
