### PR TITLE
instfiles: Add pam.d config for arch linux.

### PR DESCRIPTION
**Pull request by boppbo**
system-auth didn't work for gnome under arch linux. 

According to https://wiki.archlinux.org/index.php/PAM#PAM_base-stack system-remote-login seemed to be the right choice. Works for gnome at least.

### CODE REVIEW

**Comment by metalefty** [comment]
Also modify `configure.ac`  and `instfiles/pam.d/mkpamrules` to fully care Arch.

**Comment by metalefty** [comment]
Ah, `mkpamrules` already modified.

**Comment by boppbo** [comment]
I only found it in the description for the possible values. Was this the correct place? Furthermore the macos option was missing in the description. So I added it too

**Comment by metalefty** [comment]
Yes, that's the place.

**Comment by boppbo** [comment]
Anything else missing for merge?

**Pull request merged**
