### PR TITLE
CI: add a job with address sanitizer enabled

### PR DESCRIPTION
**Pull request by chipitsine**
this enables additional job which runs unittests with address sanitizer

I think the most interesting thing found

```
2024-05-04T22:10:46.1544435Z ==59390==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55b0c8c8a7cb at pc 0x55b0c8c1ed97 bp 0x7ffdb5f65bb0 sp 0x7ffdb5f65380
2024-05-04T22:10:46.1545346Z READ of size 1000 at 0x55b0c8c8a7cb thread T0
2024-05-04T22:10:46.1546236Z     #0 0x55b0c8c1ed96 in __asan_memcpy (/home/runner/work/xrdp/xrdp/tests/common/.libs/test_common+0xc9d96) (BuildId: 9f39a5cdc888caba15ef79957b3f1e399b300649)
2024-05-04T22:10:46.1547615Z     #1 0x7f4d874bff8a in split_string_append_fragment /home/runner/work/xrdp/xrdp/common/list.c:355:5
2024-05-04T22:10:46.1548568Z     #2 0x55b0c8c5d112 in test_list__append_fragment_fn /home/runner/work/xrdp/xrdp/tests/common/test_list_calls.c:162:20
2024-05-04T22:10:46.1549742Z     #3 0x55b0c8c75a88 in srunner_run_tagged (/home/runner/work/xrdp/xrdp/tests/common/.libs/test_common+0x120a88) (BuildId: 9f39a5cdc888caba15ef79957b3f1e399b300649)
2024-05-04T22:10:46.1550808Z     #4 0x55b0c8c5aa80 in main /home/runner/work/xrdp/xrdp/tests/common/test_common_main.c:73:5
2024-05-04T22:10:46.1551781Z     #5 0x7f4d87029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)
2024-05-04T22:10:46.1552842Z     #6 0x7f4d87029e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)
2024-05-04T22:10:46.1553990Z     #7 0x55b0c8b9cc24 in _start (/home/runner/work/xrdp/xrdp/tests/common/.libs/test_common+0x47c24) (BuildId: 9f39a5cdc888caba15ef79957b3f1e399b300649)
2024-05-04T22:10:46.1554681Z 
2024-05-04T22:10:46.1558649Z 0x55b0c8c8a7cb is located 21 bytes to the left of global variable '<string literal>' defined in 'test_list_calls.c:159:5' (0x55b0c8c8a7e0) of size 18
2024-05-04T22:10:46.1559605Z   '<string literal>' is ascii string 'fragment_ret == 1'
2024-05-04T22:10:46.1560588Z 0x55b0c8c8a7cb is located 0 bytes to the right of global variable '<string literal>' defined in 'test_list_calls.c:155:31' (0x55b0c8c8a7c0) of size 11
2024-05-04T22:10:46.1561432Z   '<string literal>' is ascii string 'split this'
2024-05-04T22:10:46.1562602Z SUMMARY: AddressSanitizer: global-buffer-overflow (/home/runner/work/xrdp/xrdp/tests/common/.libs/test_common+0xc9d96) (BuildId: 9f39a5cdc888caba15ef79957b3f1e399b300649) in __asan_memcpy
2024-05-04T22:10:46.1563615Z Shadow bytes around the buggy address:
2024-05-04T22:10:46.1564040Z   0x0ab6991894a0: f9 f9 f9 f9 00 01 f9 f9 00 00 00 06 f9 f9 f9 f9
2024-05-04T22:10:46.1564529Z   0x0ab6991894b0: 02 f9 f9 f9 02 f9 f9 f9 02 f9 f9 f9 02 f9 f9 f9
2024-05-04T22:10:46.1565009Z   0x0ab6991894c0: 02 f9 f9 f9 02 f9 f9 f9 02 f9 f9 f9 02 f9 f9 f9
2024-05-04T22:10:46.1565474Z   0x0ab6991894d0: 00 00 01 f9 f9 f9 f9 f9 00 03 f9 f9 03 f9 f9 f9
2024-05-04T22:10:46.1565928Z   0x0ab6991894e0: 00 00 00 07 f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9
2024-05-04T22:10:46.1566384Z =>0x0ab6991894f0: 00 00 00 03 f9 f9 f9 f9 00[03]f9 f9 00 00 02 f9
2024-05-04T22:10:46.1566855Z   0x0ab699189500: f9 f9 f9 f9 00 05 f9 f9 06 f9 f9 f9 02 f9 f9 f9
2024-05-04T22:10:46.1567616Z   0x0ab699189510: 01 f9 f9 f9 07 f9 f9 f9 00 00 00 00 00 00 00 00
2024-05-04T22:10:46.1568074Z   0x0ab699189520: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2024-05-04T22:10:46.1568529Z   0x0ab699189530: 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 02 f9
2024-05-04T22:10:46.1568983Z   0x0ab699189540: f9 f9 f9 f9 00 00 00 00 05 f9 f9 f9 f9 f9 f9 f9
2024-05-04T22:10:46.1569514Z Shadow byte legend (one shadow byte represents 8 application bytes):
2024-05-04T22:10:46.1569957Z   Addressable:           00
2024-05-04T22:10:46.1570269Z   Partially addressable: 01 02 03 04 05 06 07 
2024-05-04T22:10:46.1570625Z   Heap left redzone:       fa
2024-05-04T22:10:46.1571207Z   Freed heap region:       fd
2024-05-04T22:10:46.1571494Z   Stack left redzone:      f1
2024-05-04T22:10:46.1571774Z   Stack mid redzone:       f2
2024-05-04T22:10:46.1572046Z   Stack right redzone:     f3
2024-05-04T22:10:46.1572316Z   Stack after return:      f5
2024-05-04T22:10:46.1572594Z   Stack use after scope:   f8
2024-05-04T22:10:46.1572872Z   Global redzone:          f9
2024-05-04T22:10:46.1573136Z   Global init order:       f6
2024-05-04T22:10:46.1573407Z   Poisoned by user:        f7
2024-05-04T22:10:46.1573676Z   Container overflow:      fc
2024-05-04T22:10:46.1574092Z   Array cookie:            ac
2024-05-04T22:10:46.1574366Z   Intra object redzone:    bb
2024-05-04T22:10:46.1574629Z   ASan internal:           fe
2024-05-04T22:10:46.1574906Z   Left alloca redzone:     ca
2024-05-04T22:10:46.1575180Z   Right alloca redzone:    cb
```

### CODE REVIEW

**Comment by matt335672** [comment]
That looks very interesting @chipitsine - thank you.

Are you happy for me to push a fix to your branch for the detected errors?

**Comment by chipitsine** [comment]
Sure, please push

**Comment by chipitsine** [comment]
in theory, we can split code fix to separate PR (and test locally with CFLAGS/LDFLAGS), after that I can rebase

up to you

**Comment by matt335672** [comment]
That's fine - I'll push a fix anyway.

**Comment by chipitsine** [comment]
also, I'm not familiar with test automation used. maybe it allows to display errors when running, i.e. without 

`make check -j $(nproc) || (cat tests/common/test-suite.log && exit 1)`

**Comment by matt335672** [comment]
I was just going to suggest replacing `tests/common/test-suite.log` with `tests/*/test-suite.log`

**Comment by chipitsine** [comment]
> I was just going to suggest replacing `tests/common/test-suite.log` with `tests/*/test-suite.log`

I tried to upload it as artifact, but file was really small and I considered that it would be better to display in build log.

feel free to push change

**Comment by chipitsine** [comment]
there were two finding in log.
one with explicit SEGV. it might be marked for skipping when sanitizer enabled

**Comment by matt335672** [comment]
Should be OK to rebase now.

**Comment by matt335672** [comment]
I replaced the artificial SEGV with USR2 as the sanitiser doesn't do anything clever with that.

**Comment by matt335672** [comment]
Thanks @chipitsine 

Having at least some sort of dynamic analysis for the code is a step in the right direction.

**Comment by chipitsine** [comment]
your welcome)

**Pull request merged**
