### PR TITLE
Add support for statvfs() to FUSE

### LINKED ISSUE #3300: Cannot copy files into mapped drives in KDE - no free space
### xrdp version

xrdp.x86_64 1:0.10.1-1.fc41

### Detailed xrdp version, build options

~~~
xrdp 0.10.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --runstatedir=/run
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CC=gcc
      CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer 
      LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes 
      CXX=g++
      CXXFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer 
      LT_SYS_LIBRARY_PATH=/usr/lib64:
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 3.2.2 4 Jun 2024
~~~

### Operating system & version

Fedora 41

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

KDE

### Environment xrdp running on

KVM virtual machine

### What's your client?

Windows 10 RDP client

### Area(s) with issue?

File transfer / drive redirection

### Steps to reproduce

1. Fresh install Fedora 41 KDE spin
2. Install packages: `sudo dnf install -y plasma-workspace-x11 xrdp xorgxrdp`
3. Enable `xorgxrdp` in `/etc/xrdp/xrdp.ini`, then `sudo systemctl start xrdp`
4. Login to this machine using Windows 10's built-in RDP client with a mapped drive
5. Try to copy a file into `~/thinclient_drives/<YOUR_DRIVE>` graphically using Dolphin

### ✔️ Expected Behavior

Copy succeeds

### ❌ Actual Behavior

Copy fails; Dolphin indicates no free space available on drive

### Anything else?

This problem was mentioned in passing in https://github.com/neutrinolabs/xrdp/issues/1429#issuecomment-546966471:

It seems like xrdp is always reporting 0 available space on mapped drives. KDE checks this value before the copy commences, hence the error. If we instead use a tool that doesn't check it (e.g. `cp`/`mv`), the operation would succeed.

### PR DESCRIPTION
**Pull request by matt335672**
Fixes #3300 

See also #3246 

Some desktop environments are now checking for free space before copying files to a destination.

To support this, the FUSE filesystem needs to convert the `statfs()`/`statvfs()` system call to the relevant PDUs from [MS-RDPEFS]

Draft for now - I'd really appreciate comments from @tsz8899 (if possible).

**Edit 24-10-14 : No longer draft**

### CODE REVIEW

**Comment by matt335672** [comment]
A screenshot from a remote session with a 119GB C: drive and a 5MB E: drive passed through:-

```
$ df -h ~/thinclient_drives/ ~/thinclient_drives/C\:/ ~/thinclient_drives/E\:/
Filesystem      Size  Used Avail Use% Mounted on
xrdp-chansrv    0.0K  0.0K  0.0K    - /home/testuser/thinclient_drives
xrdp-chansrv    119G   53G   67G  45% /home/testuser/thinclient_drives
xrdp-chansrv    5.0M  3.6M  1.5M  71% /home/testuser/thinclient_drives
```

Because we only use a single mountpoint for the remote client (with all the drives underneath), the xrdp session is unable to distinguish between them - it just sees the mount on `~/thinclient_drives`. 

Firefox and Dolphin seem OK with this (as they presumably run `statvfs()` on the target directory), but chromium on Fedora 41 doesn't - it seems to be defaulting to the freespace as returned from the mountpoint. As a result I can't browse down to the C: drive and save anything. However, the chromium snap on Ubuntu 22.04 works OK.

**Update:** Even with some fake diskspace added, chromium on Fedora 41 won't let me save anything. This needs further investigation.

@tsz8899 - which browser/platform were you using in #3246?

**Comment by tsz8899** [comment]
On my old testing platform, there was a similar issue: "Chromium cannot browse to the C: drive." 
However, manually specifying the save path as "thinclient_drives/C/    .../.../../" allows for saving.
The environment without problems: Linux + fuse2 3 + dbus-user-session. 
problematic environment: Deepin Linux + fuse2 3 + namespace + dbus-user-session. 
The reason is that there is a conflict between fuse mounts and dbus-user-session in a namespace environment.

Effective solutions:
A. Remove dbus-user-session in the namespace environment.
B. Disable the namespace and keep fuse + dbus-user-session.

This time, a new platform was built for testing, and the operating system was updated. A similar phenomenon was discovered.
This phenomenon has likely existed in my environment for a long time, but it was difficult to detect. 
Because if there are many files in the user's personal directory, or if the file manager is set to show hidden files, it will not trigger and will work normally. 
If the newly created user directory has fewer files and hidden files are not set to display, it is more likely to trigger.  
The phenomenon: 
When using Chromium browsers based on 90 and 108, the "thinclient_drives" storage location appears grayed out when selecting a save location for the first time, preventing the path selection dialog from opening. 
After refreshing the directory in the browser, files can be recognized and saved. For example:  
A. Accessing other directories and the thinclient_drives directory once using the browser allows the browser to recognize it afterward.  
B. If the browser cannot choose the storage location, manually specifying the save path as "thinclient_drives/.../" once will make "thinclient_drives" available for the remainder of that session.  
C. Canceling the save and selecting the save location again.  
D. Alternatively, setting "thinclient_drives" as the default save path.  
In my environment, this phenomenon disappears after the file manager is set to show hidden files.

However, the Microsoft Edge for Linux browser (chromium 130) does not have this issue!  
Does the Edge browser pre-read the user directory at startup?


Adding the following code did not change the phenomenon:
~~~
static void xfuse_cb_statfs(fuse_req_t req, fuse_ino_t ino)
{
    XFS_INODE        *xinode;
    struct statvfs vfs_stats;
    memset(&vfs_stats, 0, sizeof(vfs_stats));
    vfs_stats.f_bsize = 4096;
    vfs_stats.f_frsize = 4096;
    vfs_stats.f_blocks = (long long)(8999) * 1024 * 1024 / vfs_stats.f_bsize; 
    vfs_stats.f_bfree = (long long)(8899) * 1024 * 1024 / vfs_stats.f_bsize; 
    vfs_stats.f_bavail = vfs_stats.f_bfree;
    fuse_reply_statfs(req, &vfs_stats);
~~~

minor issue that does not affect usability.:
Test environment: Deepin Debian Linux +mstsc client.
~~~
df -h ~/thinclient_drives/ ~/thinclient_drives/C\:/ ~/thinclient_drives/D\:/
xrdp-chansrv    0.0K  0.0K  0.0K    - /home/testuser/thinclient_drives
xrdp-chansrv    58G   27G   31G   47% /home/testuser/thinclient_drives  ---is OK
xrdp-chansrv    359G  178G  181G   50% /home/testuser/thinclient_drives  ---is OK
~~~

Test environment: Deepin Debian Linux + wfreerdp and xfreerdp client(maybe freerdp issue).
~~~
df -h ~/thinclient_drives/ ~/thinclient_drives/C/ ~/thinclient_drives/D/
Filesystem      Size  Used Avail Use% Mounted on
xrdp-chansrv    0.0K  0.0K  0.0K    - /home/testuser/thinclient_drives
xrdp-chansrv    23P   12P   12P   47% /home/testuser/thinclient_drives  ---size error
xrdp-chansrv    3.6P  1.7P  2.0P   50% /home/testuser/thinclient_drives  ---size error
~~~

**Comment by tsz8899** [comment]
There is a fuse mount situation that I am unsure if it is relevant:

When the system enables namespaces and removes dbus-user-session, the operating system and browser can access thinclient_drives normally.

However, when the system enables namespaces and uses dbus-user-session, 
The issue occurs 100%: the operating system can access thinclient_drives, but the browser cannot recognize the thinclient_drives (can't browse down any drive).

Feedback from the operating system developers is as follows:
The reason the program cannot receive mount events is that after setting up namespaces, a new mount namespace is created upon re-logging into the system. 
At this point, the desktop session and the mount monitoring service are located in different mount namespaces. 
This results in the mounted file systems in the desktop session not being monitored by the service, causing applications in the desktop session to be unable to receive mount events.

The suggested workaround is to try executing the mount operation through user services.
user login systemctl --user start fusemount.service

**Comment by matt335672** [comment]
Thanks @tsz8899 

Do you know what version of xfreerdp your wfreerdp client is built with? I've just tried with xfreerdp 3.7 from a Linux machine and the results seem correct.

The environment you are describing (mount namespaces and monitoring on a desktop) is unfamiliar to me. Is this a Deepin-specific feature?

My own issue with chromium on Fedora41 is different, and not namespace related. If I browse to the thinclient directory and open the save dialog box (say for an iso image), chromium starts downloading the file to the directory in a hidden file:-

<pre>
$ ls -lah ~/thinclient_drives/_home_mj/
. . .
total 0
<b>
-rw-------. 1 testuser testuser 379M Nov 11 10:59  .org.chromium.Chromium.YSyVe4
</b>
</pre>

However, the Save button is still greyed out.

**Comment by matt335672** [comment]
Just found my Chromium problem - Chromium wants `f_namemax` to be set for the filesystem.

**Comment by tsz8899** [comment]
Can we merge this function now?

**Comment by matt335672** [comment]
@tsz8899 - happy to oblige. Thanks for the conversation.

**Comment by metalefty** [comment]
@matt335672 Do you think it is safe to pick this to v0.10?

**Comment by matt335672** [comment]
Yes, I think so. I've raised #3342 and tested it on Windows 10. Feel free to merge.

**Pull request merged**
