### PR TITLE
Add ulalaca 

### PR DESCRIPTION
**Pull request by metalefty**
TODO:
* Add macOS CI to perform build test on ulalaca

### CODE REVIEW

**Comment by metalefty** [comment]
@unstabler I'm thinking of adding ulalaca like this. 

Here's our  repo:
* https://github.com/neutrinolabs/ulalaca-xrdp

Keep working on your repo, sometimes we upstream fetch from your rpeo.

**Comment by metalefty** [comment]
I'm not sure about the cppcheck error. Is it because I'm testing code written for macOS on Linux?

**Comment by matt335672** [comment]
The error is because `int XrdpUlalaca::lib_mod_start()` doesn't have a return value.

The warnings are down to missing initialisers for the specified member variables. If I understand it right this isn't a language error, but initialising member variables is one of the recommended practices in Scott Meyers' influential book "Effective C++". 

My C++ is a little rusty I'm afraid. When I've got some time I'll see if I can think of a better way to initialise this struct.

**Comment by metalefty** [comment]
@unstabler Can you have a look at this cppcheck error?

**Comment by unstabler** [comment]
@matt335672 @metalefty fixed!

**Comment by metalefty** [comment]
Thanks! I confirmed it's fixed!

**Comment by metalefty** [comment]
I'll merge this now. Let's add CI later.

**Pull request merged**
