### PR TITLE
common: add references to constants' origin

### PR DESCRIPTION
**Pull request by metalefty**
I added constants' origin AFAIK as I suggested in #947. Still WIP.

Dones:
* Add comments where the constants come from
* seperate RDP origin constants and xrdp constants

Not dones:
* sync names used in the original document
* ~~seperate RDP origin constants and xrdp constants~~

### CODE REVIEW

**Comment by jsorg71** [comment]
+1

**Comment by metalefty** [comment]
I'm adding more origins now.

**Comment by metalefty** [comment]
I added more origins, classified constants into these 5 types

* constants for xrdp
* constants come from ITU-T Recommendations
* constants come from Remote Desktop Protocol
* constants come from other MS products
* unclassified yet

**Comment by metalefty** [comment]
No logic change in this PR, adding comments and sorting only. Merging.

**Pull request merged**
