### PR TITLE
v0.8.1 release candidate

### PR DESCRIPTION
**Pull request by metalefty**
I described why I'm waiting for release v0.8.1 in #311.

There's some legal packaging works left. For example, removing 3des.
I'm testing my v0.8 branch on CentOS 7.  It is stable for me.

Jay, if you like this, let's release v0.8.1 based on this.

### CODE REVIEW

**Comment by itamarjp** [comment]
in configure.ac it says 0.9.0

https://github.com/neutrinolabs/xrdp/blob/devel/configure.ac

**Comment by metalefty** [comment]
Yes, devel branch is for future 0.9.0, right?
I'm talking about v0.8 branch.
https://github.com/metalefty/xrdp/blob/v0.8/configure.ac#L4

**Comment by itamarjp** [comment]
I strong recommend to have only one branch and use tags when I release a new version.
for example after tagging 0.9.0 change devel to 0.9.1

**Comment by metalefty** [comment]
You're correct.  Actually, it was tough for me to make this pull request.  I never want to repeat such a tough work.  The reason why I suggested v0.8.1 is Jay's comment before mentions v0.8.1 in #162 and v0.8.1 is never released for now.  Either v0.8.1 or v0.9.0 is OK for me.  Important point is to give xrdp a new release tag in order to provide full TLS support for ordinary users. 

Some people also want a new release tag these days. For example, #318, #325 just now.

I repeat what I said in #311.

> As you may know, RC4 cipher used in classic RDP encryption is considered to be no longer safe. This means xrdp v0.6.x is no longer safe when directly exposed to the internet. For this reason, I want to recommend TLS instead of classic RDP encryption. However, there's no specific version number for full TLS support. v0.8.0 is lacking some TLS fixes. Use v0.8 branch? master or devel branch? No way. It is not clear for ordinary users. If v0.8.1 is released, I can simply say "use v0.8.1 instead of v0.6.x."

There's one other thing, xrdp have neither explicit branch plan nor release cycle AFAIK.

How would you like to determine them on this opportunity? As itamarjp says, one branch is simple and easy.  +1 to this. Each new release always made from master.  And then, release cycle.  Time-based ex. quarterly, half-yearly or yearly? Or feature-based?

Thanks for your comment.

**Comment by metalefty** [comment]
Let me know your opinion what prevents making a new release.
I strongly think we want a new release tag.

**Comment by itamarjp** [comment]
@proski what do you think about ?

**Comment by metalefty** [comment]
One more suggestion about version in devel/master branch. 

The version written in [readme.txt ](https://github.com/neutrinolabs/xrdp/blob/devel/readme.txt)and [configure.ac](https://github.com/neutrinolabs/xrdp/blob/devel/configure.ac) in devel/master branch is 0.9.0 but not actually 0.9.0 because 0.9.0 has not been released yet.  This is very very confusing. I suggest stopping this. devel/branch should not be called future release version.

After 0.9.0 is released, the version may be 0.10.0 or 1.0.0 but whichever is ok. Assuming 1.0.0 at this time. Don't bump version to 1.0.0 until it actually be released.  Instead, bump version to 0.9.90 or something like this. 1.0.0 will be called 0.9.90 until release. \*.\*.90 is reserved for under development version.


[TigerVNC/tigervnc](https://github.com/TigerVNC/tigervnc) has similar idea.  How would you like this idea?

**Comment by moobyfr** [comment]
IMHO, I would prefer using several branch: the master (or devel) gets all the features. When a set of functionalities are available, create a branch (like the 0.8). Inside the branch use tags to mark releases: 0..8 0.8.1 etc... with only fixes in the 0.8 branch. but the same fixes have to be applied on the master branch too. New features only goes in the master, and when it's fully functional make another branch 0.9 and make tags inside it.
This is a method largely used in OSS projet, but it needs more work because some patchs have to be applied twice, and needs a release manager which follow changes. In the actual state where there is no human ressource to know when to make tags or release tar.gz this whould be more difficult...

Keep it simple, we need at least tags and tar.gz for the packagers, it's a pity to see that some version bundled by default in distribs are 0.5 or 0.6 , it makes a bad idea or xrdp for users which get old bugs.

**Comment by jsorg71** [comment]
Currently the way it's done, I don't think it that confusing.
devel is latest branch, use at your own risk.
At stable points, devel is merged into master.
master is considered fairly stable.
Then the marked branch v0.8 or v1.0(in the future) are the stable branches.
I've been using the odd minors for development versions like v0.7 and v0.9.
Not saying this is the way it has to be.

I'm good for this merge lets get a new release out.

I'll start a new issue for discussion on the release concerns.

**Comment by proski** [comment]
I'm not familiar with the state of the 0.8 branch. Besides, I haven't really touched X11rdp yet. I suggest that we work on stabilizing the devel branch and make a release based on it. Of my changes, I cannot think of any change that absolutely must be cherry-picked. OK, maybe "Fix building outside the source tree", it fixes a compile error after all. Maybe also the fix for the month display.

Regarding versioning, the even/odd convention is useful if there are stable and unstable releases. It was too much overhead even for Linux kernel. I would not mind if we abandon that convention.

I agree that configure.ac in git should have anything resembling a released version, unless it's a commit from which the release was made. That is, the version is 0.9-pre, it changes to 0.9.0 for one commit, from which the 0.9.0 release is made. The next commit changes it to 0.10-pre. The release branch v0.9 could use 0.9.1-pre, change to 0.9.1 for one commit, then go to 0.9.2-pre if needed.

Fedora packages "version" 0.9.0. It's their mistake. We should release something that looks newer than 0.9.0 and prevent such mistakes in the future by improving our release process.

Let's not go to v1.0 yet, we can do 0.10, 0.11 etc. Releasing 1.0 is an important message that the project can only send once in its lifetime. v1.0 should compile with all features without root access and "x-o-matic" scripts. It should compile without warnings and it should run without warnings and memory leaks in Valgrind. It should also have nice clear documentation. The point is, users who try it should be encouraged to join the project, not be put off by poor code and documentation.

**Comment by metalefty** [comment]
@proski

> configure.ac in git should have anything resembling a released version, unless it's a commit from which the release was made

That is what I wanted to say. Thank you for summarizing.

Just FYI. In FreeBSD case, not to make mistakes like Fedora's 0.9.0, packages of development snapshot has version like 0.9.0.bYYYYMMDD at my discretion. "b" stands for beta.  This ensures upcoming 0.9.0 is calculated greater than 0.9.0.bYYYYMMDD.
```
$ pkg version --test-version 0.9.0 0.9.0.b20160302
>
```
This result means 0.9.0 > 0.9.0.b20160302.

> Let's not go to v1.0 yet,

+1

@jsorg71 
> I'm good for this merge lets get a new release out.

Did you mean 0.8.1? I no longer want this to be merged.  I agree with all proski said now.

**Comment by metalefty** [comment]
@jsorg71 
> I'll start a new issue for discussion on the release concerns.
how's it going?

**Pull request closed without merging**
