### PR TITLE
Fix two issues with Microsoft Remote Desktop for MAC

### PR DESCRIPTION
**Pull request by daixj-shterm**
Fix two issues with Microsoft Remote Desktop for MAC:
```
1) Microsoft Remote Desktop 8.0.30030, Nothing displayed after log on to windows
2) Microsoft Remote Desktop 10.2.2(1291), No Fonts displayed, looks like https://github.com/neutrinolabs/xrdp/issues/643
```

### CODE REVIEW

**Comment by metalefty** [comment]
Awesome! But could you create PRs separately?

**Comment by metalefty** [comment]
Confirmed fonts are properly displayed.

**Comment by metalefty** [comment]
This fix is also effective with #367.

**Comment by daixj-shterm** [comment]
I created another PR separately just for #367, https://github.com/neutrinolabs/xrdp/pull/1235.
I will close this later.

**Pull request closed without merging**
