### PR TITLE
[v0.10] Support screens larger than 4096 pixels (update submodule)

### PR DESCRIPTION
**Pull request by metalefty**
Fixes:  #3083

---

Jay is working on NEON (accelerations for ARM64) however bug fixes should be shipped ASAP to the stable version v0.10.

### CODE REVIEW

**Comment by rowlap** [comment]
Sorry to nitpick, but can we use "pixels" spelling in the title, in aid of searching?

**Comment by metalefty** [comment]
Thanks, it was my mistake.

**Comment by metalefty** [comment]
I will correct the commit message later.

**Comment by matt335672** [comment]
LGTM

**Pull request merged**
