### PR TITLE
rfx fixes for large tile sets, performance change, Xorg will start ne…

### PR DESCRIPTION
**Pull request by jsorg71**
…xt frame earlier

### CODE REVIEW

**Comment by proski** [comment]
This patch is on the par with the existing code, but it's behind the modern standards of software engineering. Numeric constants should have names. It should be clear from the name whether 4096 is a protocol limitation, a "large enough number" or something else. If a constant number is derived from other numbers, it should be represented as an expression.

Likewise, when two variables are compared, the difference between those numbers would normally have a meaning that can be expressed with a concise term (e.g. unacknowledged packets). A local variable could be created to hold that difference and describe its meaning. That would not make the program slower; it's trivial for a compiler to optimize out local variables.

Especially when the original code didn't get it right, it's important that the code that replaces it goes beyond fixing the immediate issue.

If the code fixes issues for the users, let's merge this PR. But I cannot review this PR in a meaningful way. I can say it has no typos and gets formatting right. I could look deeper if the assumptions were expressed in the code.

**Comment by tfischer77** [comment]
As I told in #524, the PR does not solve it completely, as im some cases, at least "drects" can be > 4096. I did some tests with the code in `xrdp/xrdp_encoder.c` and ended up with this code in `process_enc_rfx`, which now runs for several hours without crashes and frozen screens:
```
    mutex = self->mutex;
    event_processed = self->xrdp_encoder_event_processed;

/*
    if ((enc->num_crects > 8192) || (enc->num_drects > 8192))
    {
        return 0;
    }
*/
    out_data_bytes = 16 * 1024 * 1024;
    index = 256 + sizeof(struct rfx_tile) * enc->num_crects +
                  sizeof(struct rfx_rect) * enc->num_drects;
    out_data = (char *) g_malloc(out_data_bytes + index, 0);
    if (out_data == 0)
    {
        return 0;
    }
    tiles = (struct rfx_tile *) (out_data + out_data_bytes + 256);
    rfxrects = (struct rfx_rect *) (tiles + enc->num_crects);

    count = enc->num_crects;

```
I don't know if I will produce any "ugly" side effects like memory leaks, but I think I will leave the code running in my test environment for some days and look what happens.

**Comment by speidy** [comment]
+1

**Comment by Natureshadow** [comment]
Btw, why are num_crects and num_drects signed integers, and the code does not check for overruns?

**Comment by Natureshadow** [comment]
What about this:

```
--- a/xrdp/xrdp_encoder.c
+++ b/xrdp/xrdp_encoder.c
@@ -22,6 +22,7 @@
 #include "xrdp.h"
 #include "thread_calls.h"
 #include "fifo.h"
+#include "limits.h"
 
 #ifdef XRDP_RFXCODEC
 #include "rfxcodec_encode.h"
@@ -320,21 +321,25 @@ process_enc_rfx(struct xrdp_encoder *sel
     mutex = self->mutex;
     event_processed = self->xrdp_encoder_event_processed;
 
-    if ((enc->num_crects > 512) || (enc->num_drects > 512))
-    {
+    out_data_bytes = 16 * 1024 * 1024;
+
+    if ((enc->num_crects > (INT_MAX / sizeof(struct rfx_tile))) ||
+        (enc->num_drects > (INT_MAX / sizeof(struct rfx_rect) -
+                            sizeof(struct rfx_tile) * enc->num_crects -
+                            256 - out_data_bytes)) ||
+        (enc->num_crects < 0) || (enc->num_drects < 0)) {
         return 0;
     }
 
-    out_data_bytes = 16 * 1024 * 1024;
-    index = 256 + sizeof(struct rfx_tile) * 512 +
-                  sizeof(struct rfx_rect) * 512;
+    index = 256 + sizeof(struct rfx_tile) * enc->num_crects +
+                  sizeof(struct rfx_rect) * enc->num_drects;
     out_data = (char *) g_malloc(out_data_bytes + index, 0);
     if (out_data == 0)
     {
         return 0;
     }
     tiles = (struct rfx_tile *) (out_data + out_data_bytes + 256);
-    rfxrects = (struct rfx_rect *) (tiles + 512);
+    rfxrects = (struct rfx_rect *) (tiles + enc->num_crects);
 
     count = enc->num_crects;
     for (index = 0; index < count; index++)
```

It does a proper check on the structure sizes the number of rects will later be used in and imposes no further artifical limits.

**Comment by proski** [comment]
Much better. There is still 256 is a couple of places, it needs to be clarified.

Please fix the reuse of the `index` variable. A variable should serve a single purpose. `index` is a very generic name. Loop variables can be `i`, `j` etc. The large number in the malloc() call could probably be `max_index`.

**Comment by jsorg71** [comment]
The 256 is an empty header that the lower layers fill out when sending.  Other parts call it pad_bytes.  Pad usually means put it at end, maybe we can thing of a better name.
num_crects and num_drects comes in as uint16 and put into int.  So it can be 0 to 64K.
https://github.com/neutrinolabs/xrdp/blob/2424a9c020d3644323caca8f29ae5b3b2c355de1/xup/xup.c#L1162-L1186

**Comment by Natureshadow** [comment]
So count yourself lucky that xrdp compiles on no system that runs on 16 bit architectures :D!

**Comment by jsorg71** [comment]
xrdp wont startup if size of int is not 4.  So far no one has asked for 16 bit int systems.  The only one I can think of is Window 3.1.
https://github.com/neutrinolabs/xrdp/blob/2424a9c020d3644323caca8f29ae5b3b2c355de1/xrdp/xrdp.c#L324-L328

**Comment by Natureshadow** [comment]
>https://github.com/neutrinolabs/xrdp/blob/2424a9c020d3644323caca8f29ae5b3b2c355de1/xrdp/xrdp.c#L324-L328


Aaah... oh. Uhu...

**Pull request merged**
