### PR TITLE
CI: add .travis.yml

### PR DESCRIPTION
**Pull request by metalefty**
Let's introduce continuous integration in order to automatically test build of pull requests.

### CODE REVIEW

**Comment by metalefty** [comment]
In order to run build tests at xrdp repo, neutrinolabs owner needs to activate repo at travis-ci.org.
Build for this PR succeeds on my fork: https://travis-ci.org/metalefty/xrdp/builds/175988615

**Comment by speidy** [comment]
I have activated it @ travis-ci.org

**Comment by proski** [comment]
Is that our recommended set of options? We should try to enable them if the needed libraries/functions exist.

I have fixes for FUSE warnings in my fuse branch, I'll split them out and submit. xorgxrdp should use silent rules by default to reduce noise.

If would be nice to compile xrdp with g++ as well. But xorgxrdp is not compilable with C++, as the X server headers are heavily abusing `class`, `private` and other C++ keywords. Maybe xorgxrdp should a separate travis file?

**Comment by metalefty** [comment]
The options are my personal recommended set. 


For xorgxrdp, it's better to create a separate travis file in xorgxrdp repo.  It can test pull requests to xorgxrdp repo.

**Pull request merged**
