### PR TITLE
V0.8uni

### PR DESCRIPTION
**Pull request by gladmouse**

### CODE REVIEW

**Comment by gladmouse** [comment]
give me a mm

**Comment by speidy** [comment]
Can you explain this PR?

**Comment by jsorg71** [comment]
this branch, v0.8uni, is a temporary branch for Univention until xrdp v0.8.1 is released.

**Comment by omkarsr** [comment]
Hi Team,
Please excuse if this a wrong thread to ask for help, I am looking for information on rail support in this version, and is there any quick instruction to test this feature using xfreerdp command line interface.

Greatly appreciate your response

Much obliged,
Omkar


Sent from my Fire

On January 12, 2015, at 5:47PM, jsorg71 <notifications@github.com> wrote:

this branch, v0.8uni, is a temporary branch for Univention until xrdp v0.8.1 is released.

**Comment by jsorg71** [comment]
I created an issue #210 for this.

**Comment by metalefty** [comment]
Closing.

**Pull request closed without merging**
