### PR TITLE
move to posix shm

### PR DESCRIPTION
**Pull request by jsorg71**

### CODE REVIEW

**Review by matt335672 — COMMENTED** [review]
Code all looks fine.

It strikes me that you could remove the older `process_server_paint_rect_shmem()` and `process_server_paint_rect_shmem_ex()` calls at this point as we're in devel and these are no longer being called by xorgxrdp. Or is this a bad idea?

**Comment by Nexarian** [comment]
@matt335672 They're still used by the GFX mainline_merge branch. Maybe a comment to merge the two is in order, but I don't want to break mainline_merge just yet, it'll take a bit to integrate with this going forward.

**Comment by matt335672** [comment]
Fine - that sounds very much like it's a 'bad idea' to remove them then!

**Comment by matt335672** [comment]
@jsorg71 - Can we merge this now?

Thanks

**Comment by Nexarian** [comment]
Just a note that I'm good with this. It will break `mainline_merge` but I'm happy to rebase and refactor on top of this. We need this change, and my AVC444 work should not be considered blocking any more.

**Review by Nexarian — APPROVED** [review]

**Comment by jsorg71** [comment]
Yes this will break mainline_merge, I'll help fix that too.

**Comment by Nexarian** [comment]
This also needs to go in: https://github.com/jsorg71/xorgxrdp/tree/posix_shm

**Comment by jsorg71** [comment]
I think that I got the xorgxrdp part done.  A good reason to leave the sysv share memory part in for a bit is that newer xrdp can work with older xorgxrdp.

**Comment by Nexarian** [comment]
This is great, I was working on adding it to `mainline_merge` today!

**Comment by jsorg71** [comment]
I had to do another PR to get everything working. #2786 That plus the PR from xorgxrdp should work.
To get xorgxrdp_helper working, I think we'll need to watch for message 64 and accept the fd and resend it.  First we should get it working in mainline_merge without xorgxrdp_helper.  I think we'll need that for message 63 too.

**Comment by Nexarian** [comment]
Cool, I'm happy to try my hand at getting this working. Not quite sure I understand how to do the handoff with xorgxrdp_helper but as you said, that comes later.

Should probably have one of our Friday chats soon. I have a lot of updates about AVC444.

**Pull request merged**
